name: CI

on: [push]

jobs:

  build:
    name: Run Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - name: ubuntu-latest
            os: ubuntu-latest
            target: linux
          - name: windows-latest
            os: windows-latest
            target: win
          - name: macOS-latest
            os: macOS-latest
            target: osx
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1


    - name: Setup NPM
      uses: actions/setup-node@v2-beta
      with:
        node-version: '10'

    - name: Build .NET solution
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      run: |
        dotnet --version
        dotnet tool install ElectronNET.CLI -g
        dotnet build ./blazor-electron-sample.sln --configuration Release

    - name: Build Electron artifact
      runs-on: ${{matrix.os}}
      run: |
        npm install
        electronize build /target ${{matrix.target}}
#        npm install


    # - name: Test .NET solution
    #   env:
    #     DOTNET_CLI_TELEMETRY_OPTOUT: 1
    #     DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    #   run: |
    #     dotnet --version
    #     dotnet test ./blazor-electron-sample.sln --configuration Release