name: CI

on: [push]

jobs:

  build:
    name: Run Build on ${{ matrix.cfg.os }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg:
          - { target: linux, os: ubuntu-latest   }
          - { target: win   , os: windows-latest }
          #- { target: osx   , os: macOS-latest }
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true


    - name: Setup NPM
      uses: actions/setup-node@v2-beta
      with:
        node-version: '10'

    - name: Build .NET solution
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      run: |
        dotnet --version
        dotnet tool install ElectronNET.CLI -g
        dotnet build ./blazor-electron-sample.sln --configuration Release

    - name: Build Electron artifact
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        electronize build /target ${{matrix.cfg.target}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: blazor-electron-sample-${{matrix.cfg.target}}
        path: "bin/[Dd]esktop/\n!bin/[Dd]esktop/*unpacked/"

    # - name: Test .NET solution
    #   env:
    #     DOTNET_CLI_TELEMETRY_OPTOUT: 1
    #     DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    #   run: |
    #     dotnet --version
    #     dotnet test ./blazor-electron-sample.sln --configuration Release